export const GET_RESTAURANTS = {
    REQUEST: "REQUEST",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE"
}

export const GET_ITEMS = {
    REQUEST: "REQUEST",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE"
}
export const CART_ITEMS = {
    ADD: 'ADD',
    REMOVE: 'REMOVE',
    CLEAR: 'CLEAR'
}

export const SELECT_RESTAURANT = "SELECT_RESTAURANT"

export const ADD_CART_RESTAURANT = "ADD_CART_RESTAURANT"
export const LOGOUT = "LOGOUT"